controllers/organization.controler.js
migrations/20220518132904-create-organization.js
models/organization.js
seeders/20220518135103-demo-organization.js

Model, migration, seed and controller for organization created.

Ot199 15 db for organization

---

controllers/member.controller.js
migrations/20220518141800-create_member.js
models/member.js
seeders/20220518142030-demo-member.js

Model, migration, seed and controller created for Members

Ot199 22 db for members

---

views/welcomeEmail.ejs

Welcome mail template used for new users of Ong.

Welcome Email tamplate made with ejs

---

controllers/user.controller.js
migrations/20200921211634-create-user.js
models/user.js
seeders/20201109013159-create-demo-user.js

- Se añadió timestamps y sofDelete en modelo User
- Se cambio el nombre del campo "image" a "photo" (para tener coherencia con el ticket)
- Se restringio valores nulos a los campos
- Se creó el controlador User

Ot199 17 user create model migration and controller

---

migrations/20220518010540-create-testimonials.js
models/testimonials.js
seeders/20220518012259-testimonials.js

Se creó el objeto para el migración, seed, el modelo y el controlador de testimonials

Ot199 20 crear modelo migracion y controlador base de testimonials

---

helpers/generateToken.js
package-lock.json
package.json

hice la lógica del JWT y lo hice con clases, que opinan de la implementación, es mi primera pull request

Añadiendo logica con JWT

---

migrations/20220518195244-create-slide.js
models/slide.js
seeders/20220523171157-demo-slides.js

Added two files.
1- slide model
2- slide migration

OT199-29 migration and model for slides

---

controllers/member.controller.js
controllers/memberController.js
controllers/organization.controller.js
controllers/organizationController.js
seeders/20220518135103-demo-organization.js
seeders/20220518142030-demo-member.js

Fix errors with controllers and seed of Member and Organization: 
- Seed: Change example seed for real seed
- Controller: Improved by adding the class

Ot199 107 error member organization

---

controllers/activity.controller.js
migrations/20220521234939-create-activity.js
models/activity.js
seeders/20220522000026-create-activities.js

Se creó el modelo Activity, con su migration, seed y controller

Ot199 21 activities create model migration and controller

---

models/member.js
models/organization.js

Primary key added in models of Organization and Members

Add primaryKey to id in Member and Organization

---

migrations/20220518010540-create-testimonials.js
models/testimonials.js
seeders/20220518012259-testimonials.js

* Se corrige tamaño columna content en testimonials
* Se agregan mas seeds
* Se cambia nombre controller
* Se agrega primary key al modelo testimonials

OT199-111 fix testimonials and migrate

---

constants/rolesUser.js
controllers/categoriesController.js
middlewares/checkRole.js

Agregado middleware para verificar el rol del usuario en sesión, se borro una lineal de espacio en el controlador de categorías, y se creo un archivo constante donde se podrá obtener id del rol correspondiente

OT199-27-Middleware-para-verificar-usuario-administrador

---

services/welcomeMail.js

* Se corrige uso de export de sendgrid

HotFIX-sendgrid-error

---

controllers/categoriesController.js
routes/categories.js

- Se modifico la fn getAllCategories
- Se devuelve solo el campo name
- Se valida si el usuario es administrador

Ot199-41-Endpoint-CategoryList

---

controllers/roles.controller.js
models/role.js
seeders/20201109013158-create-roles.js

- se generaron los distintos roles de usuarios (admin, estudiante, docente, voluntario, tutor, colaborador y visitante)
- rol model

FIX-OT199-16-Roles-Seeders

---

middlewares/checkRole.js
routes/users.js

- Se añadió el parametro next en la fn isAdmin para el correcto funcionamiento de la fn.
- Se arregló la importación del helper validateFields

OT199-114-HOTFIX-Middleware-CheckRole-isAdmin

---

controllers/categoriesController.js
routes/categories.js

Se agrego al controlador el método updateCategories que actualiza el registro de una categoria, además se cambio el numero de los status por el uso del helper httpStatus, también se agrego la ruta put para poder actualizar categorías

Ot199 44 endpoint put categorias

---

controllers/user.controller.js
middlewares/checkRole.js
routes/users.js

* Nuevo endpoint para update user
* Nuevo método en class userController para acceder base

OT199 14 Endpoint de Actualizar Usuario

---

controllers/user.controller.js

Register return a token access now.

Token in registration added

---

app.js
controllers/newsController.js
routes/news.js

Endpoint for detail news added.

Endpoint for news detail

---

controllers/categoriesController.js
routes/categories.js

Se agrego el metodo deleteCategorie donde elimina una categoría recibiendo el ID por parámetro

add delete Categorie

---

controllers/categoriesController.js
routes/categories.js

- Se agregó el endpoint GET /categories/:id
- Se creó la funcion getCategory
- Se retorna un msg y el estado 404 si la categoria no se encontró

OT199-42-Endpoint-CategoryDetail

---

services/awsS3.js
services/uploader.js

- Reusable image upload service ready. (Image validator not implemented yet)
- Fix import in 'services/awsS3.js'.

Ot199 40 image upload service

---

app.js
controllers/activity.controller.js
routes/activities.js

- Se creó el router de Activities
- Se añadió la ruta /activities
- Se creó el endpoint PUT /activities/:id
- Se creó la fn updateActivity
- Se valida que el usuario sea Admin
- Se valida campos
- Se valida la existencia de la actividad en el controlador

OT199-53-Endpoint-ActivityUpdate

---

middlewares/checkRole.js

agregando return a la funcion getData

HOTFIX return

---

app.js
controllers/activity.controller.js
package-lock.json
package.json
routes/activities.js
routes/users.js

- se creo el activity controller y los métodos para observar todas las actividades, para buscar una actividad particular y eliminar alguna actividad. Estas ultimas dos deben ser manejadas por el Admin.
- se agrego el router para activities, con los métodos get y delete.

OT199-49-Activity controller y router, ver como admin

---

seeders/20201109013158-create-roles.js
seeders/20220522000026-create-activities.js

Fix down of activities and roles seeders.

Add down for seeders of activities and fix down for roles

---

app.js
controllers/memberController.js
routes/members.js

- Se añadió el router members
- Se creó la fn deleteMember
- Se creó el endpoint DELTE /members/:id
- Se valida la existencia del miembro segun id

OT199-75-Endpoint-MembersDelete

---

controllers/memberController.js
routes/members.js

* Se crea un endpoint de getid para members
* Se agrega un métido que devuelva el objeto en controller member

Ot199 72 crear migracion y modelo de miembros

---

migrations/20220602205118-create-contact.js
models/contact.js

Se agrego los archivos de migración y modelo para el registro Contactos

OT199-55-Creación-migración-modelo-contacto

---

migrations/20220602145514-create-organizationaddcolumns.js
models/organization.js
seeders/20220602145125-organization-addcolumns.js

* Se crea un migration con addcolumn
* Se agrega a model organization las columnas nuevas
* Se crea un seed que actualiza el registro con los datos de ONG del pdf

Ot199 66 agregar campos de contacto a organizations

---

controllers/organizationController.js
migrations/20220518195244-create-slide.js
models/organization.js
models/slide.js

- Se relacionó 1:m los modelos Slides y Organization
- Se incluyen los slides en la respuesta
- Se ordena por el campo "order" de manera ascendente

OT199-62-Endpoint-AddSlidesInPublicEndpoint

---

controllers/activityController.js
package.json

Arreglando duplicados

---

controllers/sendmailController.js
controllers/userController.js
package-lock.json
services/welcomeMail.js
views/templateEmail.ejs

Se modifico algunos archivos para su reutilización y se agrego el método sendContactMail en sendMailController

OT199-64-Enviar-email-de-contacto

---

controllers/userController.js
seeders/20201109013159-create-demo-user.js

- Se corrige el hasheo del password al registrar usuario
- Se hashea el password del seed user

OT199-125-Fix-PasswordHash

---

app.js
controllers/backofficeController.js
routes/backoffice.js

* Se modifica app para nuevo route
* Se crea controller backoffice que consume método del controller contactos
* Se crea router backoffice

Ot199 65 listado de contactos

---

controllers/memberController.js
routes/members.js

* Se cambia controller members que tenía marcas de merge <<<
* Se cambia router member que importaba 2 veces checkrole

Hotfix merge members

---

controllers/backofficeController.js

* Se quita import de un objeto que no se usa

HOTFIX import incorrect

---

routes/backoffice.js

* Se agrega que valide usuario administrador al endpoint

Ot199 126 listado de contactos corregir acceso solo admin

---

controllers/testimonialsController.js
package-lock.json
routes/testimonials.js

Se agrego el metodo updateTestimonial al controlador Testimonial para su actualización en la base de datos

add updateTesmimonial controller

---

routes/activities.js
routes/contacts.js
routes/members.js
routes/slides.js

- Se añadió el middleware isAdmin, en todos los endpoints cuyas peticiones son POST, PUT y DELETE

OT199-78-Middleware-AddRoutesProtection

---

documentation/categoriesDocumentation.js

se elimino el parámetro Token de todas las rutas de Swagger

Small changes

---

README.md
seeders/20220612235213-20-users-test.js

- Seed with 10 admin and 10 no admin users to test. 
- Upgrade README with information about the test users.

Seed with test-users to test functions

---

routes/testimonials.js

arreglando permiso de usuario a la ruta de testimonios

arreglo de permiso de ruta para usuario

---

app.js
controllers/commentsController.js
routes/comments.js

endpoint de creacion de comentarios

creacion de endopint create

---

documentation/newsDocumentation.js

- Se añadió la documentación a los endpoints /news

OT199-91-NewsDocumentation

---

seeders/20220616180000-create-comments.js

OT199-130-seed-modelo-comments

---

controllers/commentsController.js
routes/comments.js

* Se crea endpoint getAll
* Se agrega método en controller comments

OT199-80-Endpoint-para-listar-Comentarios

---

app.js
controllers/slideController.js
helpers/decodeImage.js

- se hizo cambios al helpers decodeImage.
- se arreglo el order.

MEJORA DE OT199-59 Crear Slides

---

controllers/commentsController.js
routes/comments.js

* Se agrega endpoint de eliminación
* Valida que sea del usuario o admin
* Se agrega al controllador el destroy

Ot199 83 endpoint eliminación comentarios

---

documentation/testimonialDocumentation.js

Se agrego en un archivo la documentación del endpoint para utilizar con swagger ui

add testimonial documentation

---

controllers/newsController.js
test/news.test.js

Se realizó el happy path al controlador de news

OT199-98-Testing-News
